[project]
name = "gymman"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.0",
    "datetime>=6.0",
    "fastapi[standard]>=0.141.1",
    "jwt>=1.4.0",
    "psycopg>=3.3.4",
    "pwdlib[argon2]>=0.3.0",
    "pydantic>=2.13.4",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.51",
    "typing>=3.10.0.0",
]
