"""make the data primary key

Revision ID: 15fe29f69b5e
Revises: 648b25e3a857
Create Date: 2026-08-13 06:37:35.210617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15fe29f69b5e'
down_revision: Union[str, Sequence[str], None] = '648b25e3a857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mark_attendance', 'date_att',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mark_attendance', 'date_att',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
