"""add table attendance

Revision ID: 648b25e3a857
Revises: d47bbc53ac58
Create Date: 2026-08-12 09:01:14.431462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648b25e3a857'
down_revision: Union[str, Sequence[str], None] = 'd47bbc53ac58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mark_attendance',
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('date_att', sa.Date(), nullable=True),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trainer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mark_attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
