"""rename the column date

Revision ID: d47bbc53ac58
Revises: eda000221535
Create Date: 2026-08-11 11:41:37.876693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47bbc53ac58'
down_revision: Union[str, Sequence[str], None] = 'eda000221535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('date_schedule', sa.Date(), nullable=False))
    op.drop_column('schedule', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('schedule', 'date_schedule')
    # ### end Alembic commands ###
